// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umlsfsutxmvhdjogpuat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbHNmc3V0eG12aGRqb2dwdWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTE2MzQsImV4cCI6MjA2MzQyNzYzNH0.94AOVg7700rnekAMh-b_2ZpFb0oxFhxUwFTatHtPvzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);