// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izhjdgjfofxntqgrjqbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6aGpkZ2pmb2Z4bnRxZ3JqcWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDkxMzAsImV4cCI6MjA3NDMyNTEzMH0.qBTujaf_YvXROqYFhyCL-MKvhQ4H735csfH7iebBZ80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});